### PR TITLE
add matrix-stats and gmcm

### PR DESCRIPTION
**Pull request by lizhoucheng**
close https://github.com/codesignal/coderunner/issues/772 and #93 

Add matrix-stats and gmcm packages and switch back to the old way to install tryCatchLog. It builds successfully on Dockerhub.

### CODE REVIEW

**Comment by menewman** [comment]
@lizhoucheng - Not mandatory but you could also fix this bonus issue while you're in the R Dockerfile maybe? 🙏 

https://github.com/CodeSignal/dockerfiles/issues/93

**Comment by lizhoucheng** [comment]
Sure!

**Review by ivyc81 — CHANGES_REQUESTED** [review]
Looks like GMCM is not installed correctly?
This is from dockerhub(https://hub.docker.com/repository/registry-1.docker.io/codesignal/r-env/builds/9bb06b2b-2eed-4b8c-9011-daf070f0b273)
Screen Shot 2020-09-23 at 8 45 19 AM

I pulled the image and played with it on my local
Screen Shot 2020-09-23 at 8 47 27 AM

**Comment by lizhoucheng** [comment]
Good catch! I install `r-base-dev` which we should install since we are using `install.packages()`. (ref: https://cran.r-project.org/bin/linux/ubuntu/README.html). It fixes the problem

**Review by ivyc81 — APPROVED** [review]
🎉 Good job finding the missing puzzle to install GMCM!

**Pull request merged**
