### PR TITLE
Add r-cran-tryCatchLog

### PR DESCRIPTION
**Pull request by menewman**
[no issue]

I really want to add this for the sake of being able to print proper runtime error stack traces in R.

https://cran.r-project.org/web/packages/tryCatchLog/index.html

Confession: I didn't test that this works.

### CODE REVIEW

**Comment by Albinutte** [comment]
@menewman any chance you have a code snippet I should try running to make sure the package works?

**Comment by menewman** [comment]
@Albinutte -
```r
library(tryCatchLog)
```

**Comment by Albinutte** [comment]
@menewman Thanks!

Are you going to publish this image and update image version in the `coderunner` repo? Should we open an issue for that

**Comment by menewman** [comment]
@Albinutte - Yes, I will open an issue!

**Comment by Albinutte** [comment]
I'm gonna wait for some tests before approving this 🙃

**Comment by menewman** [comment]
yeah it doesn't work :(

**Comment by Albinutte** [comment]
Classic R.

**Comment by menewman** [comment]
I was just kind of throwing darts in the dark on this one. I have a better idea for how to do this; will come back to it in a bit.

**Pull request closed without merging**
