### PR TITLE
CoffeeScript and TypeScript Ubuntu 20.04

### LINKED ISSUE #254: Update typescript image to support new Ubuntu version

### PR DESCRIPTION
**Pull request by ArDrambyan**
Closes #254 #253 

## Changes

Updated `coffeescript` and `typescript` docker images to derive from `codesignal/js:new` image to be based on Ubuntu 20.04

### CODE REVIEW

**Comment by ArDrambyan** [comment]
You can see that coderunners `142.93.253.158` and `206.189.185.112` are passing all the tests

**Comment by ArDrambyan** [comment]
@menewman - pinging in case if you missed this PR 😅

**Comment by menewman** [comment]
> @menewman - pinging in case if you missed this PR 😅

@ArDrambyan - Oh hey! Thanks for reminding. Yes, I did. Looks like this one slipped by is because I'm not listed as a requested reviewer, and I exclusively use GitHub's review-requested list to remind myself what's in my review queue:
https://github.com/pulls/review-requested

For example, this is what I see now:
Screen Shot 2021-02-22 at 12 21 13 PM

No biggie; you probably just assigned without requesting review & I didn't check the email notifications carefully enough. I'll take a look at it today. 👍

**Review by menewman — APPROVED** [review]
:shipit:

**Comment by ArDrambyan** [comment]
> Looks like this one slipped by is because I'm not listed as a requested reviewer, and I exclusively use GitHub's review-requested list to remind myself what's in my review queue:

I'm always requesting review and assigning the reviewer, this time somehow I forgot to request a review 😅

**Pull request merged**
