### PR TITLE
Update .NET Core version from 2.2 to 3.0

### LINKED ISSUE #89: Upgrade to .NET Core 3.0
Just released. Might as well bump up from 2.2 to 3.0; it's supposed to be backwards-compatible.

### PR DESCRIPTION
**Pull request by menewman**
Closes #89.

Updates the .NET Core installation from version 2.2 to 3.0, which was released very recently.

https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0

I am not yet sure if this Docker image will be backwards compatible with existing content, so that's something we should test before releasing new coderunners pointing at this image.

**Testing:**
Expand the "All checks have passed" section below and view the successful image built on Docker Hub.

### CODE REVIEW

**Comment by menewman** [comment]
@artahian - I know pinging on review after only 6 hours is a little aggressive, but... I'm going to do it anyway because I really want to work on the follow-up PR. 🙃

**Comment by Albinutte** [comment]
And I really want to work on my follow-up PR 🙃

**Comment by menewman** [comment]
@artahian - Ping!

**Comment by artahian** [comment]
@menewman sorry for the late response, it might not be very logical but pinging me makes it worse because the email gets bumped up to the top and I usually go through pending github emails bottom to top :)

**Comment by menewman** [comment]
I use this link instead of relying on my email:
https://github.com/pulls/review-requested

**Pull request merged**
