### PR TITLE
Java bump; gradle support

### PR DESCRIPTION
**Pull request by Albinutte**
Updates Java version to 11 in both main and Java dockerfiles, and adds Gradle to Java dockerfile.

### CODE REVIEW

**Comment by Albinutte** [comment]
@ksaxberg this PR also fixes Java in main dockerfile; we'll need to merge it today so that we could redeploy prod coderunners.

**Comment by Albinutte** [comment]
@ksaxberg this is just Dockerfile update; I'll be using this image to create test wrapper & stuff. Will try defining ENVs in a single command 👍

**Comment by ksaxberg** [comment]
You don't have to update the ENVs. It looks like there's an issue with clojure, I'm getting syntax error on the "hello" test

**Comment by Albinutte** [comment]
Clojure split is good to go 👍 Let's get all these PRs merged, and update coderunner to use correct VMs for different testing tools!

**Comment by Albinutte** [comment]
(as in, I don't want to touch that main `Dockerfile` pls)

**Pull request merged**
